# vim: ts=4 st=4 sr noet smartindent:
AMI_SOURCE_CHANNEL?=stable
AMI_SOURCE_GIT_BRANCH?=*
AMI_SOURCE_GIT_REPO?=*
AMI_SOURCE_GIT_SHA?=*
AMI_SOURCE_GIT_TAG?=*
export AWS_DEFAULT_REGION?=eu-west-1
export AWS_INSTANCE_TYPE?=t2.large
export BUILD_AMI_GIT_TAG?=
export PACKER_DEBUG?=
export PACKER_DIR?=./
export PACKER_LOG?=
export EUROSTAR_PRODUCT?=
export EUROSTAR_ROLE?=
export EUROSTAR_BUILD_VERSION?=
